stages:
  - validate
  - binaries
  - packages
  - upload
  - announce

.release:
  only:
    - tags
  except:
    - master

.build_package:
  stage: packages
  extends:
    - .release
  script:
    - ci/build_package
  needs:
    - build:binaries
  artifacts:
    paths:
      - .result/
    expire_in: 30m

.upload_package:
  stage: upload
  extends:
    - .release
  image: registry.gitlab.com/alxrem/package_cloud
  script:
    - ci/upload_package

validate:
  stage: validate
  image: alpine
  extends:
    - .release
  script:
    - apk -U add git
    - ci/validate_version

build:image:
  stage: packages
  image: docker:latest
  services:
    - docker:19.03.15-dind
  except:
    - master
  script:
    - ci/build_image

build:binaries:
  stage: binaries
  extends:
    - .release
  image: golang:1.13-alpine
  script:
    - apk add -U binutils
    - ci/build_binaries
  artifacts:
    paths:
      - binaries/
    expire_in: 30m

build:stretch:
  extends:
    - .build_package
  image: debian:stretch

upload:stretch:
  variables:
    DIST: debian/stretch
  extends:
    - .upload_package
  needs:
    - build:stretch

build:buster:
  extends:
    - .build_package
  image: debian:buster

upload:buster:
  variables:
    DIST: debian/buster
  extends:
    - .upload_package
  needs:
    - build:buster

build:xenial:
  extends:
    - .build_package
  image: ubuntu:xenial

upload:xenial:
  variables:
    DIST: ubuntu/xenial
  extends:
    - .upload_package
  needs:
    - build:xenial

build:bionic:
  extends:
    - .build_package
  image: ubuntu:bionic

upload:bionic:
  variables:
    DIST: ubuntu/bionic
  extends:
    - .upload_package
  needs:
    - build:bionic

announce:
  stage: announce
  extends:
    - .release
  image: python:3-alpine
  needs:
    - build:binaries
    - job: upload:stretch
      artifacts: false
    - job: upload:buster
      artifacts: false
    - job: upload:xenial
      artifacts: false
    - job: upload:bionic
      artifacts: false
  script:
    - pip install requests
    - apk -U add git
    - ci/gitlab_release
